"""Regenerate vendored protobuf stubs from embedded descriptors.

The original `.proto` sources are not present in this repository. The existing
generated modules still embed the serialized `FileDescriptorProto` payloads, so
we can rebuild modern descriptor-pool based `_pb2.py` files directly from those
descriptors without changing the wire schema.
"""

from __future__ import annotations

import importlib.util
import sys
import types
import warnings
from pathlib import Path

from google.protobuf import descriptor_pb2

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "custom_components" / "mysolid" / "_proto"
MODULE_NAMES = (
    "android_checkin_pb2",
    "checkin_pb2",
    "mcs_pb2",
)


def main() -> None:
    modules = _load_modules(SOURCE_DIR)
    for module_name in MODULE_NAMES:
        module = modules[module_name]
        rendered = _render_module(module)
        (SOURCE_DIR / f"{module_name}.py").write_text(rendered, encoding="utf-8")


def _load_modules(proto_dir: Path) -> dict[str, types.ModuleType]:
    package_name = "_mysolid_proto_regen"
    package = types.ModuleType(package_name)
    package.__path__ = [str(proto_dir)]  # type: ignore[attr-defined]
    sys.modules[package_name] = package

    loaded: dict[str, types.ModuleType] = {}
    for module_name in MODULE_NAMES:
        loaded[module_name] = _load_module(package_name, proto_dir / f"{module_name}.py", module_name)
    return loaded


def _load_module(package_name: str, path: Path, module_name: str) -> types.ModuleType:
    qualified_name = f"{package_name}.{module_name}"
    spec = importlib.util.spec_from_file_location(qualified_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[qualified_name] = module
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        spec.loader.exec_module(module)
    return module


def _render_module(module: types.ModuleType) -> str:
    descriptor = module.DESCRIPTOR
    file_proto = descriptor_pb2.FileDescriptorProto()
    file_proto.ParseFromString(descriptor.serialized_pb)

    import_lines = []
    if file_proto.dependency:
        for dependency in file_proto.dependency:
            dependency_module = f"{Path(dependency).stem}_pb2"
            dependency_alias = dependency_module.replace("_", "__")
            import_lines.append(f"from . import {dependency_module} as {dependency_alias}")

    imports_block = "\n".join(
        [
            "from google.protobuf import descriptor as _descriptor",
            "from google.protobuf import descriptor_pool as _descriptor_pool",
            "from google.protobuf import symbol_database as _symbol_database",
            "from google.protobuf.internal import builder as _builder",
            *([""] + import_lines if import_lines else []),
        ]
    )

    return "\n".join(
        [
            "# -*- coding: utf-8 -*-",
            "# Generated by the protocol buffer compiler.  DO NOT EDIT!",
            f"# source: {descriptor.name}",
            '"""Generated protocol buffer code."""',
            imports_block,
            "",
            "# @@protoc_insertion_point(imports)",
            "",
            "_sym_db = _symbol_database.Default()",
            "",
            "",
            f"DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile({descriptor.serialized_pb!r})",
            "",
            "_globals = globals()",
            "_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)",
            "_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, __name__, _globals)",
            "",
            "# @@protoc_insertion_point(module_scope)",
            "",
        ]
    )


if __name__ == "__main__":
    main()
