# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: android_checkin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15android_checkin.proto\x12\rcheckin_proto"\x8a\x03\n\x10ChromeBuildProto\x12:\n\x08platform\x18\x01 \x01(\x0e2(.checkin_proto.ChromeBuildProto.Platform\x12\x16\n\x0echrome_version\x18\x02 \x01(\t\x128\n\x07channel\x18\x03 \x01(\x0e2\'.checkin_proto.ChromeBuildProto.Channel"}\n\x08Platform\x12\x10\n\x0cPLATFORM_WIN\x10\x01\x12\x10\n\x0cPLATFORM_MAC\x10\x02\x12\x12\n\x0ePLATFORM_LINUX\x10\x03\x12\x11\n\rPLATFORM_CROS\x10\x04\x12\x10\n\x0cPLATFORM_IOS\x10\x05\x12\x14\n\x10PLATFORM_ANDROID\x10\x06"i\n\x07Channel\x12\x12\n\x0eCHANNEL_STABLE\x10\x01\x12\x10\n\x0cCHANNEL_BETA\x10\x02\x12\x0f\n\x0bCHANNEL_DEV\x10\x03\x12\x12\n\x0eCHANNEL_CANARY\x10\x04\x12\x13\n\x0fCHANNEL_UNKNOWN\x10\x05"\xf6\x01\n\x13AndroidCheckinProto\x12\x19\n\x11last_checkin_msec\x18\x02 \x01(\x03\x12\x15\n\rcell_operator\x18\x06 \x01(\t\x12\x14\n\x0csim_operator\x18\x07 \x01(\t\x12\x0f\n\x07roaming\x18\x08 \x01(\t\x12\x13\n\x0buser_number\x18\t \x01(\x05\x12:\n\x04type\x18\x0c \x01(\x0e2\x19.checkin_proto.DeviceType:\x11DEVICE_ANDROID_OS\x125\n\x0cchrome_build\x18\r \x01(\x0b2\x1f.checkin_proto.ChromeBuildProto*g\n\nDeviceType\x12\x15\n\x11DEVICE_ANDROID_OS\x10\x01\x12\x11\n\rDEVICE_IOS_OS\x10\x02\x12\x19\n\x15DEVICE_CHROME_BROWSER\x10\x03\x12\x14\n\x10DEVICE_CHROME_OS\x10\x04B\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, __name__, _globals)

# @@protoc_insertion_point(module_scope)
